### ISSUE TITLE
dynamic shards not available for use in development mode but available in production mode

### ISSUE THREAD

**Issue by baseliners** [thiagopradi/octopus#103]
I'm using the dynamic shard initialization approach mentioned on the wiki. The code is in an initializer called dynamic_shards.rb in config/initlaizers. Immediately after initializing the shards, if I try to use one of them within the initializer file, the shard is not recognized. Here's my code in dynamic_shards.rb:

begin
  shards = {:my_shards => {}}
  #initialize shards here ...
  ...

 Octopus.setup do |config|
    config.shards = shards
    config.environments = [:development, :production, :staging]
  end

rescue ActiveRecord::StatementInvalid => e
  puts e
end
# try to use one of the shards

Octopus.using(:xyz) do
  puts "test"
end

In development mode, I get an error while trying to use the xyz shard that was initialized: Nonexistent Shard Name: xyz

In production mode, this works fine.

I've been trying to look at the configs in development.rb and production.rb to see if any of them might be responsible but I've ruled out this possibility by swapping in the production.rb contents into development.rb and still getting the same error in development mode. 

Btw, in development mode, if I try to use one of the dynamically initialized shards in a controller, I have no issues. It's just within the initializer file itself. I'm trying to setup an application-level config parameter (that requires info from the shards) in the initializer that can then be used across the app.

Is this to be expected? If not, any way to get this to work the same in development mode as well? Thanks.

**Comment by flushentitypacket** [comment]
@baseliners Did you ever get that fixed? I'm experiencing the same problem on 0.6.1.
