### ISSUE TITLE
Named scopes is not working on shards

### ISSUE THREAD

**Issue by kirandarisi** [thiagopradi/octopus#164]
Hi,

Named scopes are not working on shards. For example please take a look at the below code 

class User < ActiveRecord::Base
  named_scope :premium_accounts, {:conditions => {:name => "kiran"}}
end

and if i run using 

Octopus.using(:shard_name) do 
  User.premium_accounts
end

the query is going for master DB rather than shard

Thanks
Kiran

**Comment by arojoal** [comment]
I have this same problem with Octopus 0.9.2 and Rails 5.1.5 but only when running from Rails Console.
