### ISSUE TITLE
undefined method `initialize_shards' when using Octopus.setup

### ISSUE THREAD

**Issue by aub** [thiagopradi/octopus#173]
I'm trying to initialize Octopus with the dynamic Octopus.setup method rather than through the YAML file, like so:

``` ruby
Octopus.setup do |config|
  config.environments = [:production, :development, :test]
  config.shards = { client_data: shards }
end
```

This gives me an undefined method `initialize_shards' error when I bootstrap rails on the call to config.shards because that method assumes that the AR connection is already an Octopus::Proxy. Perhaps I'm doing something wrong, but I don't see how the connection would have ever been replaced by the proxy in the code. In my case, the connection is an ActiveRecord::ConnectionAdapters::Mysql2Adapter.

**Comment by joongimin** [comment]
@troessner I ran into the same problem and fixed it by calling `gem 'composite_primary_keys'` prior to calling `gem 'ar-octopus'`. This makes composite_primary_keys initialize before Octopus thus not corrupting `Octopus::Model.hijack_methods`.
