### ISSUE TITLE
schema.rb does not update all migrations

### ISSUE THREAD

**Issue by michaelachrisco** [thiagopradi/octopus#295]
schema.rb will only reflect database.yml and not the shards.yml on Octopus. 

I have a new project:

``` Bash
$ rails new octopi_multi_test
```

Add gem ar-octopus to gemfile

``` Ruby
#Gemfile
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.8'
# Use sqlite3 as the database for Active Record
gem 'activerecord-jdbc-adapter'
gem 'activerecord-jdbcsqlite3-adapter'
gem 'jdbc-mysql', :platform => :jruby
gem 'mysql2', :platform => :ruby
# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.3'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development
gem 'ar-octopus'

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
```

``` Bash
$ rails g model Drivers name:string firstname:string lastname:string
$ rails g model OtherDrivers name:string firstname:string lastname:string
```

``` Ruby
#20150107223214_create_drivers.rb
class CreateDrivers < ActiveRecord::Migration
  using(:services)
  def change
    create_table :drivers do |t|
      t.string :name
      t.string :firstname
      t.string :lastname

      t.timestamps
    end
  end
end

#20150107223321_create_other_drivers.rb
class CreateOtherDrivers < ActiveRecord::Migration
  using(:api)
  def change
    create_table :other_drivers do |t|
      t.string :name
      t.string :firstname
      t.string :lastname

      t.timestamps
    end
  end
end
```

``` Ruby
# database.yml
# SQLite version 3.x
#   gem 'activerecord-jdbcsqlite3-adapter'
#
# Configure Using Gemfile
# gem 'activerecord-jdbcsqlite3-adapter'
#
default: &default
  adapter: sqlite3

development:
  <<: *default
  database: db/services_dev.sqlite3

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: db/services_test.sqlite3

production:
  <<: *default
  database: db/services.sqlite3
```

``` Ruby
# shards.yml
octopus:
  environments:
    - development
    - production
    - test
  development:
    api:
      adapter: sqlite3
      database: db/api_dev.sqlite3

    services:
      adapter: sqlite3
      database: db/services_dev.sqlite3

  production:
    api:
      adapter: sqlite3
      database: db/api.sqlite3

    services:
      adapter: sqlite3
      database: db/services.sqlite3

  test:
    api:
      adapter: sqlite3
      database: db/api_test.sqlite3

    services:
      adapter: sqlite3
      database: db/services_test.sqlite3

# default_migration_group: services
```
- If the database.yml has api as its database, the schema version will be 20150107223321 and will not include OtherDrivers migration in schema.rb
- If the database.yml has services as its database, the schema version will be 20150107223214 and will not include Drivers migration in schema.rb

**Comment by michaelachrisco** [comment]
db/migrate looks like:
```
20150107223214_create_drivers.rb
20150107223321_create_other_drivers.rb
20150107223429_create_drivers_agains.rb
```
After ```bundle exec rake db:migrate```
Schema looks like: 
```Ruby
ActiveRecord::Schema.define(version: 20150107223321) do

  create_table "other_drivers", force: true do |t|
    t.string   "name"
    t.string   "firstname"
    t.string   "lastname"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end

```

**Comment by lukeasrodgers** [comment]
@michaelachrisco what do you think `db/schema.rb` should look like in this scenario? If it had tables from both shards, then that would mean that someone just geting started with this code (a new developer on your team), would run `rake db:setup` or whatever, and they'd end up with both tables in whichever db was set in `database.yml`, which is not the setup you want.

It would be great if somehow all the built-in Rails schema.rb stuff could "just work" in a sharded environment, but I think that's just not possible without overhauling how Rails handles that file, and how it handles migrations.

**Comment by michaelachrisco** [comment]
I'm thinking of using db/shards/<shardname>_schema.rb
to at least reflect each schema in each db. The seedbank does something similar with their gem. 

schema.rb should at least have the latest migration number: ```ActiveRecord::Schema.define(version: <latestmigration>) do``` when doing a migration.

Currently looking at the gem tapsoob to export the schema.rb from each db no matter what the database. Let me know if you have any suggestions. We are using octopus as a multisharding tool between our API's and user profiles. :)

**Comment by lukeasrodgers** [comment]
`schema.rb` having the latest migration number sort of makes sense, except in a sharded environment, it seems to me that no given database is the "master," so it seems like it makes sense for that file to only track the migrations on that database (i.e. the default one in `database.yml`). And if you decide to somehow use multiple `_schema.rb` files, which seems like an approach that is worth pursuing, then each would only have the migration number for its own relevant migrations.

**Comment by michaelachrisco** [comment]
That is the plan at least. It would make debugging the sharded environments easier without doing too much to Rails default behavior. It would be even better to create custom rake tasks the same way as seebank and call ```bundle exec rake db:<shardname>:<subshard option...etc>: migrate``` which would build each shard and only include each applicable migration number (as you suggested).

**Comment by michaelachrisco** [comment]
I haven't had the time to look at this issue in full but https://github.com/azitabh/multi-database-migrations might be a good start for an optional gem onto Octopus. Make multiple migrations and schema.rb's on each db.
