### ISSUE TITLE
Potential issue with Octopus.using block

### ISSUE THREAD

**Issue by jamesfzhang** [thiagopradi/octopus#306]
Do you expect these 2 code blocks to return the same result? Should `@keyboard` equal `@keyboard2`?

``` ruby
Octopus.using(:brazil) { @keyboards = Keyboard.where('id is not null') }
Octopus.using(:brazil) { @keyboard = @keyboards.first }
```

vs

``` ruby
Octopus.using(:brazil) { @keyboard2 = Keyboard.where('id is not null').first }
```

The first code block actually evaluates the query using the master shard whereas the second code block uses the brazil shard. Here's the sql log:

```
Keyboard Load (0.3ms)  SELECT `keyboards`.* FROM `keyboards` WHERE (id is not null)
[Shard: brazil]  Keyboard Load (0.4ms)  SELECT  `keyboards`.* FROM `keyboards` WHERE (id is not null)  ORDER BY `keyboards`.`id` ASC LIMIT 1
```

**Comment by thiagopradi** [comment]
Hi @jamesfzhang - 

I'm trying to close old issues here. I think your problem was fixed a while ago - I've added a test case (https://github.com/thiagopradi/octopus/commit/cac326954e3d9094418b248dedad93325fb45b0b) to make sure it doesn't break anymore.

Thiago
