### ISSUE TITLE
Getting "undefined method `__method__'" when running RSpec specs

### ISSUE THREAD

**Issue by jipiboily** [thiagopradi/octopus#309]
Hey there,
I am trying to use Octopus with those instructions https://devcenter.heroku.com/articles/distributing-reads-to-followers-with-octopus so we use can use a follower DB for some metrics stuff. I followed the instructions and reviewed pretty much everything in the wiki but I can't find what I am doing wrong.

I am getting this for a ton of specs:

```ruby
undefined method `__method__' for #<ActiveRecord::Associations::CollectionProxy []>
```
I guess a few things to note:
- we are using Spring, but I fixed the problems I had with it via https://github.com/tchandy/octopus/issues/303#issuecomment-98840215. The error from this very issue I am writing right now was present before that fix for Spring.
- we are indeed using a bunch of Gem, none seems obviously a problem, but it could happen.
- I did not change anything in my code besides the configuration link on GitHub and a few background jobs (using queue_classic) that are wrapped in `Octopus.using(:followers)` blocks. Those are failing with a different error that I hope will be easier to figure out. The error is `Nonexistent Shard Name: followers`.
- while I know it would not have been a solution, I tried removing the inclusion of the collection proxy [here](https://github.com/tchandy/octopus/blob/master/lib/octopus/collection_proxy.rb#L16) by disabling, and it still fills the same way

Any idea what it could be? Where to look at?

Thanks!

**Comment by sobrinho** [comment]
Did you tried to remove spring and see if the problem still happens? Can you provide the backtrace?

**Comment by angelim** [comment]
Just bumped into a similar problem on a Rails 3.2 app. Instead of `undefined method '__method__'` I was getting `private method '__method__' called` on every `assigns(:items).should == [item]` of my controllers specs. However, if I use something like `assigns(:items).to_a.should == [item]` it works without any issues.
There's a quick fix for this particular case, but I don't know if it may cause any other side effects: changing `@ar_relation.public_send to @ar_relation.send`

```ruby
module Octopus
  class RelationProxy
    def method_missing(method, *args, &block)
      run_on_shard { @ar_relation.send(method, *args, &block) }
    end
  end
end
```

**Comment by jipiboily** [comment]
Sorry for never replying @sobrinho, apparently I didn't see the notification on that one. I don't know what I was working on using Octopus at that time, but I don't have any work to do with it these days, sorry.

**Comment by jipiboily** [comment]
Ah, I remember now, but yeah, I'm not working there anymore and that project was either put on hold or I think we in fact changed our approach. Feel free to close, unless @angelim reports is related and relevant to you.

**Comment by selenetelenav** [comment]
I'm also getting this error, and @angelim's fix does not work for me. I am making our specs shard-aware, so there's code in spec helper that  uses DatabaseCleaner to open a transaction on the specified shard and wrap the spec in `Octopus.using`.

Spec:

    describe "some spec", shard: :other_shard do
      before do
        @group = Factory :group  # ActiveModel stored on :other_shard, has relation `has_many :buckets`
        @group.buckets.stub(:to_csv).and_return('CSV_STRING')   # Fails with undefined method `__method__' for #<ActiveRecord::Associations::CollectionProxy []>
      end
    end

The `stub` line is what's failing. If I change to use the RSpec 3 `allow` syntax, it winds up calling the original method:

    describe "some spec", shard: :other_shard do
      before do
        @group = Factory :group  # ActiveModel on a separate shard with has_many :buckets
        @group.buckets.stub(:to_csv).and_return('CSV_STRING')
      end
      it "should return the stubbed value" do
          @group.buckets.to_csv.should eq 'CSV_STRING'  # Calls the original, not the stub
      end
    end

**Comment by jcoleman** [comment]
I've submitted a patch to RSpec for this issue. See https://github.com/rspec/rspec-expectations/pull/898

**Comment by sobrinho** [comment]
@jcoleman there is nothing needed to be done on the octopus side then?

**Comment by jcoleman** [comment]
@sobrinho Correct. The patch to RSpec has actually already been merged in, though I'm not sure when the next release will be. Either way, devs affected by this error can either pin RSpec to the latest master or wait for the next gem release.

**Comment by sobrinho** [comment]
Great, closing!
