### ISSUE TITLE
Database connections

### ISSUE THREAD

**Issue by jeremymarc** [thiagopradi/octopus#340]
I have setup octopus with 1 master and 2 slaves.

Here the configuration:
=> {"replicated"=>true, "fully_replicated"=>true, "environments"=>["production"], "production"=>{"purple_follower"=>{"adapter"=>"postgresql", "database"=>"xxx", "username"=>"xxx", "password"=>"xxx", "host"=>"xxxx", "pool"=>25, "port"=>5812, "octopus_shard"=>"purple_follower"}, "bronze_follower"=>{"adapter"=>"postgresql", "database"=>"yyy", "username"=>"yyy", "password"=>"yyy", "host"=>"yyy", "pool"=>25, "port"=>6132, "octopus_shard"=>"bronze_follower"}}}

When running pg:info, Im getting the exact same connections on all database:
=== follower1
Connections:        85/400
=== follower2
Connections:        85/400
=== master
Connections:        87/400

Is that a normal behavior? I was expecting the number of connections to be split over the 3DB.

**Comment by thiagopradi** [comment]
Hi @jeremymarc ,

Trying to close old issues here. Yes ,Octopus should not open the same number of connections to all database -they should be split. I believe it was fixed on a few changes that we did to Octopus::Proxy.

Closing this issue.

Thiago
