### ISSUE TITLE
create a rubygems release to publish fix for inherited models

### ISSUE THREAD

**Issue by jdoconnor** [thiagopradi/octopus#346]
@sobrinho - 

you fixed this issue here https://github.com/thiagopradi/octopus/commit/558ca8833d3c479fef470e9313e928b1145d6d4a

in response to a bug report here https://github.com/thiagopradi/octopus/issues/219

This would be beneficial to release for gems that utilize octopus internally (I have a few engines that could use this)

**Comment by thiagopradi** [comment]
hey @sobrinho - any chances that you could release a new version? thanks.

**Comment by sobrinho** [comment]
@thiagopradi I think I don't have permission to publish the gem, could you make the release?

**Comment by abMatGit** [comment]
@sobrinho @thiagopradi any updates on this? Looking forward to point to a version instead of the ref tag on octopus.

**Comment by thiagopradi** [comment]
New gem was released a long time ago, closing this issue :)
