### ISSUE TITLE
ar-octopus (0.8.5), rails (4.2.4), Current shard is reseted in block when  'each' or 'map' methods are triggered on ActiveRecord::Associations::CollectionProxy objects.

### ISSUE THREAD

**Issue by biscar** [thiagopradi/octopus#347]
Current shard is reseted in block when  'each' or 'map' methods are triggered on ActiveRecord::Associations::CollectionProxy objects.

I have master and main_1 shards.
```
class Customer < ActiveRecord::Base
  has_many :orders
end
```
I think it is incorrect behavior:
```
customer = Customer.first; #master shard
puts Octopus.using(:main_1) { customer.orders.map { |op| ActiveRecord::Base.connection.current_shard } }
[:master, :master, :master] - #should be [:main_1, :main_1, :main_1]

Octopus.using(:main_1) do
customer = Customer.first
 puts Octopus.using(:master) { customer.orders.map { |op| ActiveRecord::Base.connection.current_shard } }
end
[:main_1, :main_1, :main_1] #should be [:master, :master, :master]
```
Rails 3: customer.orders returns a Array.
Rails 4: customer.orders returns a 'ActiveRecord::Associations::CollectionProxy' object

Methods map, each etc. are not available for 'ActiveRecord::Associations::CollectionProxy' object.

As result 'method_missing'(octopus/relation_proxy.rb) method is triggered and Octopus resets current shard and sets it in shard of owner(customer object) (octopus/collection_proxy.rb).

I think it is correct behavior:
```
customer = Customer.first; #master shard
puts Octopus.using(:main_1) { customer.orders.to_a.map { |op| ActiveRecord::Base.connection.current_shard } }
[:main_1, :main_1, :main_1] - is correct behavior

puts Octopus.using(:main_1) { Customer.first.orders.map { |op| ActiveRecord::Base.connection.current_shard } }
[:main_1, :main_1, :main_1] - is correct behavior
```

We see a different behavior in Rails 3:
```
customer = Customer.first; #master shard
puts Octopus.using(:main_1) { customer.orders.map { |op| ActiveRecord::Base.connection.current_shard } }
 [:main_1, :main_1, :main_1]
```
I think shoud be same behavior in Rails 3 and Rails 4.
Could you fix this, please?

**Comment by biscar** [comment]
Might you check my fix?
https://github.com/biscar/octopus/commit/44ec699708e4d793f86471ff84c6d2dd27047a9d

**Comment by sobrinho** [comment]
If you load the object from master shard, the orders should be loaded from master shard, that's correct.

In other words, associations are loaded from the same shard of the owner, that's why the block isn't affecting the load of them.

Although if you query another object like this:

``` ruby
customer = Customer.first

puts Octopus.using(:shard_1) { ActiveRecord::Base.connection.current_shard }
```

It should output `:shard_1`.

**Comment by biscar** [comment]
Your example is right.
But the below example works incorrectly.
```
customer = Customer.first
puts Octopus.using(:main_1) { customer.orders.map { |op| ActiveRecord::Base.connection.current_shard } }
```
Output is `:master` but should be `:shard_1`

 If we add `to_a` before `map` , the example will work correctly: 
```
customer = Customer.first
puts Octopus.using(:main_1) { customer.orders.to_a.map { |op| ActiveRecord::Base.connection.current_shard } }
```
Output is `:shard_1`

**Comment by biscar** [comment]
Different outputs in above cases is a dangerous situation.

**Comment by biscar** [comment]
Rails version | Example | Output 
------------ | ------------ | -------------
|3|```customer = Customer.first;puts Octopus.using(:main_1) { customer.orders.map { |op| ActiveRecord::Base.connection.current_shard } }```| master
|4|```customer = Customer.first;puts Octopus.using(:main_1) { customer.orders.map { |op| ActiveRecord::Base.connection.current_shard } }```|:heavy_exclamation_mark:main_1

**Comment by sobrinho** [comment]
Closed by pull request.
