### ISSUE TITLE
Specify minimum Ruby version

### ISSUE THREAD

**Issue by budmc29** [thiagopradi/octopus#351]
After installing the latest version using 
```
gem 'ar-octopus', :git => "git://github.com/tchandy/octopus.git", :require => "octopus"
```
i got this error:
```
undefined method `prepend` for ActiveRecord::ConnectionAdapters (...)
```
, meaning that i need Ruby > 2.0

Could you please add a note somewhere for future users, what is the minimum required version of Ruby.
I would like to find the latest version that is compatible with Ruby 1.9.3, because we need that version for legacy reasons.

Thank you very much.

**Comment by thiagopradi** [comment]
Fixed by https://github.com/thiagopradi/octopus/commit/119281b37bf16c2a6faf8e26d8e31263786558f6
