### ISSUE TITLE
dynamic shard config

### ISSUE THREAD

**Issue by warp-linden** [thiagopradi/octopus#358]
Following the example in the wiki...

/Users/warp/development/linden/ruby/gems/indra-inventory-ruby-sdk/vendor/ruby/1.9.1/gems/ar-octopus-0.8.5/lib/octopus.rb:109:in `shards=': undefined method `initialize_shards' for #<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x007fb0abcc36d0> (NoMethodError)

**Comment by anhkind** [comment]
It seems that you haven't required `ar-octopus` gem in your code, that's why the `ActiveRecord::Base.connection` didn't return `Octopus::Proxy` but the original `Mysql2Adapter`.

**Comment by warp-linden** [comment]
I have included it.  Doesn't this do the trick in a Gemfile?

gem 'ar-octopus', :require => 'octopus'

**Comment by anhkind** [comment]
What is the output of `ActiveRecord::Base.connection.class` in the console? Is it `Octopus::Proxy` or anything else?

**Comment by warp-linden** [comment]
it returns ActiveRecord::Base when I use either dynamic configuration or environment settings in my shards.yml.  If I avoid those two things, all is well.
