### ISSUE TITLE
Why is this 2nd test scenario expected to work?

### ISSUE THREAD

**Issue by oogali** [thiagopradi/octopus#359]
https://github.com/thiagopradi/octopus/blob/master/spec/octopus/proxy_spec.rb#L188

The test case is creating a new user within the ```russia``` shard, modifying it, and saving it.

It evaluates two scenarios:
- can we find the updated record on the specified shard?
- can we find the updated record on master (no shard specified)? 

Why is the 2nd scenario expected to pass?

**Comment by anhkind** [comment]
I think it's because the same user is also saved to `master` shard after the line 185. The User instance won't keep the shard info with it, so when the instance is saved, the proxy will come in and decide what shard to be used, which is `master` after the line 185.
