### ISSUE TITLE
[HELP] Need implementation guidance

### ISSUE THREAD

**Issue by kirantpatil** [thiagopradi/octopus#366]
## Our scenarios is 

1) Replicate certain User tables from Master (Cloud) to Slave (Local) and User authentication is done via Master DB

2) When there is Master DB/Internet failure the User authentication is done from Slave and the modifications to User table are saved in Slave DB

3) Once Master DB/Internet comes up, we need to apply the User DB changes from Slave to Master DB

4) After certain interval again perform step 1 (ie. replicate Master to Slave)
## Setup Details

Remote server : Microsoft SQL

Local server: Postgres/Mysql on Linux

Does octopus helps me to implement this scenario ? 

Please recommend the solution to achieve the same.

Thanks.

**Comment by thiagopradi** [comment]
HI @kirantpatil,

As the issue tracker is reserved for bug of the gem, and not architecture discussions, I'm going to close your issue.

Thiago
