### ISSUE TITLE
Session data not stored in sessions table in database

### ISSUE THREAD

**Issue by ravi-juhomi** [thiagopradi/octopus#370]
Hi ,

I have my sessions table in database and once i try to login my session values not stored in database.
I had did everything to make this work i enabled "config.action_controller.session_store = :active_record_store" and i have users in my user table too when i try to login session table is not getting inserted with user id. What could be the issue where i made a mistake.

My application is running on ubuntu server and ruby version is 1.8.7  
Rails  2.3.18
Help will be much appriciated....

**Comment by thiagopradi** [comment]
Hi @ravi-juhomi ,

Rails 2.3.18 is not supported by the latest version of Octopus.

Closing this issue.

Thiago
