### ISSUE TITLE
Drop support for Ruby 2.0.0

### ISSUE THREAD

**Issue by mikeastock** [thiagopradi/octopus#373]
Are there plans to only support > Ruby 2.1.0 in the near future? I recently opened #372 that uses required keyword arguments but that is only support in Ruby 2.1.0 and beyond. Thanks!

**Comment by thiagopradi** [comment]
hi @mikeastock - I've started working on a new version of Octopus (on branch https://github.com/thiagopradi/octopus/tree/octopus_09) that will drop support for Ruby 2.0 / Rails 3.2
