### ISSUE TITLE
PG::ConnectionBad in Resque?

### ISSUE THREAD

**Issue by s12chung** [thiagopradi/octopus#376]
I made an new clean app on heroku `follower-test.herokuapp.com` ([repo](https://github.com/s12chung/test_follower)) following [these heroku instuctions](https://devcenter.heroku.com/articles/distributing-reads-to-followers-with-octopus) on [this commit](https://github.com/s12chung/test_follower/commit/660bd693bb8c5a5ed7f1bb2ac6792c8d1675aff8). you can see the `resque` errors [here](http://follower-test.herokuapp.com/resque/failed).

this [commit](https://github.com/s12chung/test_follower/commit/efe03c77c7a8a7fb60c16c20682babb8223f6fc6) works. but i don't think it's a good idea to remove the `before/after` fork code. 

this [commit](https://github.com/s12chung/test_follower/commit/c66d8748d1c2f7bec35bb79bf87c30acdb8bf897) leads to the last error in the [resque page](http://follower-test.herokuapp.com/resque/failed).

this [commit](https://github.com/s12chung/test_follower/commit/cd5e445ce950e984bdb78091b7830a5acfc2fe27) to the second last error on the page.

another note. locally, it works without the `before/after` fork code too.

any help would be great.... thanks.

**Comment by s12chung** [comment]
for anyone looking around:
- `resque (1.25.2)` - no forking code
- `activerecord (4.2.6)` - see below:

```ruby
before_fork do |server, worker|
      if defined?(ActiveRecord::Base)
        ActiveRecord::Base.connection_proxy.instance_variable_get(:@shards).each do |shard, connection_pool|
          connection_pool.disconnect!
        end
      end
    end
after_fork do |server, worker|
      if defined?(ActiveRecord::Base)
        ActiveRecord::Base.connection_proxy.instance_variable_get(:@shards).each do |shard, connection_pool|
          connection_pool.clear_reloadable_connections!
        end
      end
    end
```

**Comment by ananth99** [comment]
This seems to be happening with Phusion Passenger as well. Our Rescue workers are not able to establish a connection with postgresql
This is the error I'm seeing in the rescue. 
We use a single shard and we use octopus to redirect few actions to fetch data from the shard.

`ActiveRecord::StatementInvalid
PG::ConnectionBad: connection is closed: SELECT a.attname, format_type(a.atttypid, a.atttypmod), pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod FROM pg_attribute a LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum WHERE a.attrelid = '"users"'::regclass AND a.attnum > 0 AND NOT a.attisdropped ORDER BY a.attnum`

**Comment by lorainekv** [comment]
I noticed that adapting [this config](https://github.com/thiagopradi/octopus/issues/319#issuecomment-253539208) for the Resque.before_fork and Resque.after_fork hooks resolved Resque BadConnection issues after adding octopus.

Something like this: 
```
Resque.before_fork do
  if defined?(ActiveRecord::Base)
    begin
      if defined?(Octopus) && Octopus.enabled?
        ActiveRecord::Base.connection_proxy.clear_all_connections!
      else
        ActiveRecord::Base.connection.disconnect!
      end 
    rescue ActiveRecord::ConnectionNotEstablished
      nil 
    end 
  end 
end

Resque.after_fork do
  if defined?(ActiveRecord::Base)
    ActiveRecord::Base.establish_connection
    if defined?(Octopus) && Octopus.enabled?
      ActiveRecord::Base.connection_proxy.initialize_shards(Octopus.config)
    end 
  end 
end
```

**Comment by dondeng** [comment]
I was having issues with Resque jobs after adding octopus and suggestion by @lorainekv above did the trick for me. Thanks.
