### ISSUE TITLE
Can't load octopus

### ISSUE THREAD

**Issue by minhyeok4dev** [thiagopradi/octopus#378]
I just add gem 'ar-octopus' but can't run server.
Do you know it? and how fix it?

I'm using Rails5 & Ruby 2.3.0, attach the error log.

Type `rails s`

/Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'ar-octopus'. (Bundler::GemRequireError)
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
	from /Users/minhyeok4dev/Documents/lookpin/lookpin-server/config/application.rb:17:in `<top (required)>'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:88:in `require'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:88:in `block in server'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/minhyeok4dev/Documents/lookpin/lookpin-server/bin/rails:9:in `require'
	from /Users/minhyeok4dev/Documents/lookpin/lookpin-server/bin/rails:9:in `<top (required)>'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `load'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `call'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/client/command.rb:7:in `call'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/client.rb:30:in `run'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/bin/spring:49:in `<top (required)>'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `load'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/minhyeok4dev/Documents/lookpin/lookpin-server/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'/Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:80:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'ar-octopus'. (Bundler::GemRequireError)
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
	from /Users/minhyeok4dev/Documents/lookpin/lookpin-server/config/application.rb:17:in `<top (required)>'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:88:in `require'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:88:in `block in server'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:85:in `tap'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:85:in `server'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/railties-5.0.0.rc1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/minhyeok4dev/Documents/lookpin/lookpin-server/bin/rails:9:in `require'
	from /Users/minhyeok4dev/Documents/lookpin/lookpin-server/bin/rails:9:in `<top (required)>'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `load'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `call'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/client/command.rb:7:in `call'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/client.rb:30:in `run'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/bin/spring:49:in `<top (required)>'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `load'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/minhyeok4dev/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/minhyeok4dev/Documents/lookpin/lookpin-server/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by angelicas** [comment]
I'm having this issue too. Were you able to resolve this?

**Comment by angelicas** [comment]
hm this issue https://github.com/thiagopradi/octopus/issues/379 helped me. I just moved it down in the Gemfile.

**Comment by thiagopradi** [comment]
Octopus support for Rails 5 will be released soon. In the meanwhile, please us directly from this branch: https://github.com/thiagopradi/octopus/compare/octopus_09 .
