### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by simonmorley** [thiagopradi/octopus#383]
By the local looks of things, this repo is sadly becoming a forgotten relic. 

Are there plans to continue supporting it? Has anyone forked and is maintaining a newer version. 

We're seeing issues with the latest Rails 4 so I'm unsure I want to invest time implementing it in out project if it's abandoned.

**Comment by agibralter** [comment]
@simonmorley what kind of issues are you seeing with Rails 4? I'm just curious for my own use case.

**Comment by simonmorley** [comment]
It never used the slave as far as I remember. Ended up using Makara instead. Never looked back.

**Comment by thiagopradi** [comment]
hi @simonmorley @fagiani - I'll have some free time in the next couple months. I can't promise that I'll be 100% dedicated to Octopus, but I'll certainly make it Rails-5 compatible and fix the main issues. Anyway, I recommend you to contribute :-)
