### ISSUE TITLE
Cross-shard Associations

### ISSUE THREAD

**Issue by tibbon** [thiagopradi/octopus#390]
If I have tables that aren't replicated across shards, I have a hard time using AR relationships (`has_many`, `belongs_to`, etc) since I can't set the shard as an option for the relationship. The following is a decent example of what's breaking. I have a huge table of tweets on a second shard, but the second shard doesn't contain the `users` table, so the associations break. 

```
# Only on shard1 (master shard)
class User < ActiveRecord::Base
  has_many :tweets
end

# Only on shard2
class Tweet < ActiveRecord::Base
  belongs_to :user
end

tweet = Tweet.first
tweet.user # PG::UndefinedTable: ERROR: relation "users" does not exist
```

I'd love a way to override it like the following, but I can't seem to get it to work:
```
class Tweet < ActiveRecord::Base
  belongs_to :user, -> { User.using('shard1').find(user_id) }
end
```

Currently, I have to override the AR methods with an instance method to set the shard, which feels sloppy and puts a lot of code in the wrong classes to make it work. My Tweets class shouldn't need instance methods to know much about the User.

**Comment by thiagopradi** [comment]
Hi @tibbon,

I'm trying to close old issues here. I can see your use case, but Octopus doesn't support it. I think this will add more complexity - and we will need to have to disable a few internal checks to support it. 

However, feel free to send a patch if you want - I'm happy to review and discuss about a possible merge.

Closing this issue.

Thiago
