### ISSUE TITLE
Rails5 not supported?

### ISSUE THREAD

**Issue by Fuffi** [thiagopradi/octopus#391]
We're getting this error when trying to upgrade our project to Rails 5
```
Bundler::GemRequireError: There was an error while trying to load the gem 'octopus'.
Gem Load Error is: uninitialized constant ActiveRecord::Associations::HasAndBelongsToManyAssociation
```

**Comment by thiagopradi** [comment]
Octopus support for Rails 5 will be released next week. In the meanwhile, you can use it from this branch: https://github.com/thiagopradi/octopus/tree/octopus_09.
