### ISSUE TITLE
Object allocations doubles

### ISSUE THREAD

**Issue by leonelgalan** [thiagopradi/octopus#392]
I just installed ar-octopus (0.8.6), with the following commit: https://gist.github.com/leonelgalan/9064695727b1b06c6eb28b0834a96fb0

I wasn't even using the shards yet, and average response time and object allocations almost doubled:

![screen shot 2016-11-11 at 3 46 04 pm](https://cloud.githubusercontent.com/assets/727774/20229863/c4da8c5e-a826-11e6-9eb1-6795266f0a03.png)

![screen shot 2016-11-11 at 3 46 28 pm](https://cloud.githubusercontent.com/assets/727774/20229874/d02fb872-a826-11e6-929c-b5bd14b6c72c.png)

I've read #280, but couldn't tell if this is a related issue. I understand 0.8.6 was released after merging the fixes discussed there.

**Comment by thiagopradi** [comment]
Hi @leonelgalan ,

Trying to close the old issues here - I think your problem was solved by #280. Please reopen if not.

Closing this issue.

Thiago
