### ISSUE TITLE
Set Default Shard by Model?

### ISSUE THREAD

**Issue by tibbon** [thiagopradi/octopus#394]
If I have a user model, and it always lives on a shard called `foo`, is there a way to do the following, so that something like `User.find(1)` executes on the `foo` database shard? 

```ruby
class User < ActiveRecord::Base
  default_shard :foo
end
```

**Comment by thiagopradi** [comment]
Hi @tibbon, 

Trying to close old issues here - For setting a default shard to a model, you need to use the `octopus_stablish_connection` method, which is explained here: https://github.com/thiagopradi/octopus#mixing-octopus-with-the-rails-multiple-database-model

Closing this issue.

Thiago
