### ISSUE TITLE
Move data between shards?

### ISSUE THREAD

**Issue by smitchelus** [thiagopradi/octopus#404]
I have the need, under certain business conditions, to move a single record from one shard to another. From reading README I thought this was something that Octopus supported, but I don't see how to go about it. Is this something that can be done?

**Comment by thiagopradi** [comment]
Hi @smitchelus - 

Trying to close old issues here - if you alter the `current_shard` attribute from a record to another and hit `save`, Octopus will save it correctly on the new database.

Closing this issue.

Thiago
