### ISSUE TITLE
How to disable ActiveRecord SQL Caching for queries on shards

### ISSUE THREAD

**Issue by mabdelfattah** [thiagopradi/octopus#405]
I'm using Octopus (latest version) with Rails (latest version) and ActiveAdmin on 2 DBs, one master for writes and one slave for reads. The problem now is, when we add any new DB entry, it is being written to the DB, but it is not being displayed on the index page because the query was cached before we create the new records!

Any solution for this problem?

**Comment by ashish-sjc** [comment]
try this in the `application_controller.rb`

```ruby
  before_action :clear_active_record_query_cache

  def clear_active_record_query_cache
    ActiveRecord::Base.connection.clear_query_cache
  end
```

**Comment by timfsw** [comment]
I've discovered the same problem. Is there any other solution than clearing the cache manually?

**Comment by timfsw** [comment]
The problem is that _query_cache_enabled_ is false for every shard instead of the value of the master shard.

> shards[Octopus.master_shard].connection.query_cache_enabled

```ruby
module Octopus
  class Proxy
    def safe_connection(connection_pool)
      connection_pool.automatic_reconnect ||= true
      if !connection_pool.connected? && shards[Octopus.master_shard].connection.query_cache_enabled
        connection_pool.connection.enable_query_cache!
      end
      connection_pool.connection
    end
  end
end
```

Any ideas for solving this problem?

**Comment by woohoou** [comment]
Same problem here, any solution of this?

**Comment by ashish-sjc** [comment]
This is an issue with RAILS 5.1, I reverted to RAILS 5.0.1 & things went to work fine

**Comment by HFYEH** [comment]
In the source code, it seems that ActiveRecord will clear query cache every time it check in connection.

https://github.com/rails/rails/blob/d6466beb9fff9f2ba4f73673e65f087dd6bba488/activerecord/lib/active_record/connection_adapters/abstract/query_cache.rb#L9

Simply change what @timfsw mentioned in Octopus to
```
# config/initializers/octopus.rb
module Octopus
  class Proxy
    def safe_connection(connection_pool)
      connection_pool.automatic_reconnect ||= true
      if !connection_pool.connected? && shards[Octopus.master_shard].connection.query_cache_enabled
        connection_pool.connection
      end
      connection_pool.connection
    end
  end
end
```
may solve this issue. However, it means no query caches are performed...

I don't know why Octopus can skip the hook method in ActiveRecord, anyone can help?

**Comment by woohoou** [comment]
@thiagopradi Any idea to solve this?
Thanks for the hard work

**Comment by lunaru** [comment]
I can confirm this is a problem on Slave reads. Octopus 0.9.1 and Rails 5.1.5.

**Comment by swordfish444** [comment]
We too are experiencing this. 

`Octopus 0.9.1  |  Rails 5.1.5`

**Comment by lunaru** [comment]
@swordfish444 we eventually went with @ashish-sjc's suggestion above and fortunately it's working out, but I do wish it were addressed natively by octopus.

**Comment by jwilsjustin** [comment]
Does anyone know if the behavior changed in Rails 5.2?

**Comment by swordfish444** [comment]
@lunaru I ended up using @timfsw's solution and it resolved the issue.

@jwilsjustin I'm not sure. We are running Octopus in production on Rails 5.1.5 and its been stable for over 1 month now.

**Comment by SixiS** [comment]
Ahhh - got stuck so long figuring out where the cache was happening!
Thanks so much for this fix @sekiyama58

@thiagopradi would be great if you could tag a release with this fix included :)

**Comment by hmatsuda** [comment]
@sekiyama58 Thanks! Our rails-5.1 application works fine.
@thiagopradi would be great if you could release new gem version with this fix included!

**Comment by woohoou** [comment]
@thiagopradi Thank you!!, it works great.
