### ISSUE TITLE
Raw Sql and Octopus.

### ISSUE THREAD

**Issue by LorneCurrie** [thiagopradi/octopus#408]
Not sure if this has been asked before.

I would like to implement this GEM, but I would like to ask one question

How would I handle scenarios where I have a few queries that we use ActiveRecord::Base.connection.raw_connection.exec_params(...., ....).  Is there anything in Octopus that will allow me to continue to implement this query in the current fashion and use Octopus' load balancing or would it be suggested that I place the RAW sql queries into a view and attach the view to a model?

**Comment by thiagopradi** [comment]
hey @LorneCurrie - a little late, but Octopus allow you to use the raw connection normally. You just need to specify what connection you want to run this query by using ``Octopus.using``.

Thiago
