### ISSUE TITLE
Cannot compare models

### ISSUE THREAD

**Issue by kaspernj** [thiagopradi/octopus#410]
```ruby
user_normal = User.find(1)
user_shard = User.using(:follower).find(1)

user_normal == user_shard #=> false
```

I would expect this to return true.

**Comment by thiagopradi** [comment]
@kaspernj - this is the expected behavior for Octopus. We use the current_shard for the comparison of equality. However, if you want to change this behavior, you can rewrite your `==` method on the ActiveRecord::Base to not consider the current shard.

Thiago

**Comment by dccunha** [comment]
There is a possible solution for it here #384 

Why can't it be used?

**Comment by thiagopradi** [comment]
@dccunha - due to the nature of the gem, I've decided to take current_shard into account when comparing records. However, you are free to rewrite your custom equality comparison logic to not consider the current shard.

Thiago
