### ISSUE TITLE
find_each does not work on rails 5

### ISSUE THREAD

**Issue by garytaylor** [thiagopradi/octopus#414]
Because the "load_records" method in the active record relation is now protected, the octopus relation proxy using "public_send" in method missing does not work.  This causes find_each to break

**Comment by thiagopradi** [comment]
hey @garytaylor - thanks for the report. Can you provide a failing SPEC for that case?

**Comment by thiagopradi** [comment]
Also, I've added two specs (https://github.com/thiagopradi/octopus/commit/78a20afa23c400f73df09fa827361ef90b18f89b and https://github.com/thiagopradi/octopus/commit/3e159241dc1d01fb3069e3389880e3df92360e25) to make sure those methods are working.

**Comment by mahemoff** [comment]
Quick fix for anyone experiencing "NoMethodError: protected method `load_records' called" error - put this in application.rb or a config/initializer file:

```
module Octopus
  class RelationProxy < BasicObject
    def method_missing(method, *args, &block)
      if block
        @ar_relation.send(method, *args, &block)
      else
        run_on_shard { @ar_relation.send(method, *args) }
      end
    end
  end
end
```

(Replaced public_send with send in [RelationProxy](https://github.com/thiagopradi/octopus/blob/46f0b4c8244f19cf6ac3c89baa0884b8b3a572fb/lib/octopus/relation_proxy.rb))

**Comment by thiagopradi** [comment]
Since we now have tests on the test suite, and those are already green, I'm going to close this issue - feel free to reopen if the problem persists.
