### ISSUE TITLE
The published gem is not updated with the latest commits from master

### ISSUE THREAD

**Issue by elisei-timofte** [thiagopradi/octopus#435]
- ar-octopus 0.9.0
- rails 5.1.1

I run into an error like 'alias_method_chain is missing'. After some debugging I've discovered that I didn't had the latest version of [this](https://github.com/thiagopradi/octopus/blob/068a64fe3442d674da5fd7f5386088f19297f27d/lib/octopus/model.rb) file. 

I've forced the Bundler to required the gem from GitHub instead of RubyGems.org (`gem 'ar-octopus', :git => 'https://github.com/thiagopradi/octopus', :require => "octopus"`)

Please republish the gem version and let us know when this is fixed.

Thanks!

**Comment by thiagopradi** [comment]
hey @elisei-timofte - that's weird. I'll publish a new release this week. Thanks for the report.

**Comment by elisei-timofte** [comment]
Thanks. Please let me know after you publish the new release.

**Comment by elisei-timofte** [comment]
Any updates on this?

**Comment by thiagopradi** [comment]
with a few months of delay, the new version of Octopus has been published. closing this issue.
