### ISSUE TITLE
has_and_belongs_to_many with :association_foreign_key fails with rails 5.1

### ISSUE THREAD

**Issue by libc** [thiagopradi/octopus#444]
Good day,

has_and_belongs_to_many can't be used with [some] options in rails 5.1 + octopus.

Reproduce code:

```ruby
class Post < ApplicationRecord
  has_and_belongs_to_many :posts, association_foreign_key: 'parent_id'
end
```

Fails on load with
```/Users/eugene/.rvm/gems/ruby-2.4.1/gems/activesupport-5.1.2/lib/active_support/core_ext/hash/keys.rb:79:in `block in assert_valid_keys': Unknown key: :association_foreign_key. Valid keys are: :class_name, :anonymous_class, :foreign_key, :validate, :autosave, :table_name, :before_add, :after_add, :before_remove, :after_remove, :extend, :primary_key, :dependent, :as, :through, :source, :source_type, :inverse_of, :counter_cache, :join_table, :foreign_type, :index_errors (ArgumentError)```

Roughly what happens is this:

```ruby
module TotallyRails
  def has_and_belongs_to_many(name, scope = nil, **options)
    p scope: scope, options: options
  end
end

module Octopus
  def has_and_belongs_to_many(name, scope = nil, options = {})
    super
  end
end

class RailsWithOctopus
  include TotallyRails
  include Octopus
end

class RailsWithoutOctopus
  include TotallyRails
end

# prints {:scope=>{:key=>:value}, :options=>{}}
RailsWithOctopus.new.has_and_belongs_to_many(:hello, key: :value)
# prints {:scope=>nil, :options=>{:key=>:value}}
RailsWithoutOctopus.new.has_and_belongs_to_many(:hello, key: :value)
```

[octopus uses `options={}`](https://github.com/thiagopradi/octopus/blob/601d2ddce4477863c091bf2c2ba09c7e8c1024e7/lib/octopus/association_shard_tracking.rb#L47) while [rails 5.1 uses `**options`](https://github.com/rails/rails/blob/v5.1.2/activerecord/lib/active_record/associations.rb#L1828)

Let me know if you need more info.

**Comment by swordfish444** [comment]
@libc Do you know any workarounds to get around this until octopus supports Rails 5.1?

**Comment by libc** [comment]
@swordfish444 nope, we're using rails 5.0 at the moment. This was the first issue I've encountered while trying to upgrade to 5.1.

**Comment by swordfish444** [comment]
@thiagopradi Is this something you are aware of? Do you have the bandwidth to address this in the near-future?

**Comment by thiagopradi** [comment]
hey @swordfish444 @libc - I'm probably won't have time to look at this issue this week, but I'm happy to review and merge a patch to fix the problem.

Thiago

**Comment by swordfish444** [comment]
@thiagopradi As you suggested, https://github.com/thiagopradi/octopus/pull/453

It would be great to get a new release out next week. This will enable Rails 5.1+ to start using Octopus.

**Comment by thiagopradi** [comment]
@swordfish444 - as the patch has been merged and a new release was created, I'm going to close this issue.
