### ISSUE TITLE
AR Migrations for All Shards

### ISSUE THREAD

**Issue by adomokos** [thiagopradi/octopus#459]
In our use case, we need to send migration changes to the `:master` and all sharded databases. Does octopus support that feature? I did not find it in the docs and in the specs.

**Comment by adomokos** [comment]
This is my attempt to solve it: https://github.com/KennaSecurity/octopus/pull/1

I can't submit a PR to Octopus, as we are stuck on version 0.9.0, due to [this issue](https://github.com/thiagopradi/octopus/issues/447).

**Comment by adomokos** [comment]
This is my attempt to solve it: https://github.com/KennaSecurity/octopus/pull/1

I can't submit a PR to Octopus, as we are stuck on version 0.9.0, due to this issue.

**Comment by thiagopradi** [comment]
Hi Attila,

As we talked via e-mail, I'm going to close your issue.

Thanks,

Thiago

**Comment by satyanash** [comment]
> As we talked via e-mail, I'm going to close your issue.

Can we elaborate on what was discussed. Currently, there doesn't seem to be a straightforward way to run migrations on _all_ shards.
