### ISSUE TITLE
Offering Help/Support

### ISSUE THREAD

**Issue by adomokos** [thiagopradi/octopus#460]
@thiagopradi,

thank you so much for creating and maintaining Octopus.

As we shard our monolithic database, we (@ [KennaSecurity](https://www.kennasecurity.com/)) rely quite heavily on this project.
However, I see little movement and activity as far as issues and PRs are addressed.

Both I and my employer would be happy to provide more help. I'd much rather do that than fork the project.

Please email me at `adomokos` at Google's email if you are interested in this.

Thank you!
Attila

**Comment by thiagopradi** [comment]
Hi Attila,

As we talked via e-mail, I'm going to close your issue.

Thanks,

Thiago
