### ISSUE TITLE
Rails 5.2: ActiveRecord::Migrator NameError

### ISSUE THREAD

**Issue by kraflab** [thiagopradi/octopus#477]
In ActiveRecord 5.2, the class method `ActiveRecord::Migrator.migrate` is removed, leading to a `NameError` in `octopus/migration.rb` file:

```
NameError: undefined method `migrate' for class `#<Class:ActiveRecord::Migrator>'
/usr/local/bundle/gems/ar-octopus-0.9.2/lib/octopus/migration.rb:69:in `alias_method'
```

Snippet of source:
```ruby
module Octopus
  module Migrator
    def self.included(base)
      base.extend(ClassMethods)

      base.class_eval do
        class << self
          alias_method :migrate_without_octopus, :migrate # NameError here
          alias_method :migrate, :migrate_with_octopus
```

The Rails commit introducing this change is here: https://github.com/rails/rails/commit/a2827ec9811b5012e8e366011fd44c8eb53fc714#diff-8d3c44120f7b67ff79e2fbe6a40d0ad6L1005

"The refactoring here moves the class methods from the `Migrator` class into it's own new class `MigrationContext`. The goal was to move the `migrations_paths` method off of the `Migrator` class and onto the connection."

**Comment by jchappelle** [comment]
Any updates on a fix for this? It's preventing me from using octopus in a new project.

**Comment by jchappelle** [comment]
I never solved it. I ended up using a different gem to get the job done.

**Comment by tusharkhatri02** [comment]
@jchappelle Can you please let me know the name of the gem ? I am also stuck. Thanks :)

**Comment by jchappelle** [comment]
@tusharkhatri02 the gem is [active_record_slave](https://github.com/rocketjob/active_record_slave). That project has less features but it is simple and did what I needed. 

Thanks @pboling . I will give it another try as soon as I can.
