### ISSUE TITLE
RelationProxy didn't correct handle block in Rails 5

### ISSUE THREAD

**Issue by elct9620** [thiagopradi/octopus#478]
The Rails 5 changes ActiveRecord loads record behavior.

```
# Rails 4
user
  .user_items # Load records!
  .map(&:item_id)

# Rails 5
user
  .user_items
  .map(&:item_id)  # Load records!
```

In this case, the RelationProxy cannot correctly execute the `map` with the block.

```
 def method_missing(method, *args, &block)
      if block # Didn't check when we using a method already exists
        @ar_relation.public_send(method, *args, &block)
      else
        run_on_shard do
          if method == :load_records
            @ar_relation.send(method, *args)
          else
            @ar_relation.public_send(method, *args)
          end
        end
      end
    end
```

This will cause us got an empty array.

**Comment by swordfish444** [comment]
@elct9620 Can you open a PR with the proposed fix? It's not clear if this is an issue in Octopus, and rather a symptom of lazy loading with the structure of your query. 

Starting with Rails 4+, ActiveRecord is putting a lot of attention into performance by preventing unnecessary n+1 queries where possible. Here is a good [post](https://revs.runtime-revolution.com/conditional-eager-loading-in-rails-9b1c1c592897) that helps explain why the loading of records is being delayed.

Your example, demonstrates how ActiveRecord no longer evaluates the associations query until an array method is called on the query, in which case it loads the records first then runs the operation. I'll test this using Octopus and see if I can confirm the bug.

**Comment by sekiyama58** [comment]
Hi, I am investigating the same issue. 
In old Rails 4.2 + Octopus 0.8.7, the code below was following the shard over the association,
but in Rails 5.1 + Octopus 0.9.2, it takes the associated data from `:master`, which corrupts the application.

```
User.using(:brazil).projects.where('1=1').map(&:name)
```

I'm also trying to fix the issue addressed by @elct9620, ( enum method chaining like `@users.each_with_index.map {}` ) in #483.
