### ISSUE TITLE
Could we start a list of products using Octopus? 

### ISSUE THREAD

**Issue by shyam-habarakada** [thiagopradi/octopus#479]
I can start and a wiki page has been setup here https://github.com/thiagopradi/octopus/wiki/Who-is-using-Octopus%3F

Lets keep this issue open so more people who come back can hopefully see it and add to the wiki?

**Comment by thiagopradi** [comment]
@shyam-habarakada - wrapping up a few pending issues here. Since the page was created , I'm closing this issue. Great to see the list of companies using Octopus!!
