### ISSUE TITLE
Could not obtain a database connection issue

### ISSUE THREAD

**Issue by kavitakanojiya** [thiagopradi/octopus#506]
I have configured the replica database with the parameters:
1. adapter
2. host
3. username
4. password
5. database
6. port
7. reconnect
8. encoding
except for the pool size.

So far, I have noticed if any parameters are missed, it picks up from the database.yml. In this case, we have the `pool size` set to 25 across beanstalk and ECS services.

Below is the attached shards.yml:

  octopus:
  
    replicated: false

    fully_replicated: false

    environments:

      - production

      replica1:

        adapter: mysql2

        host:     <%= config['host'] %>

        username: <%= config['username'] %>

        password: <%= config['password'] %>

        database: <%= config['database'] %>

        port:     <%= config['port'] %>

        reconnect: true

        encoding: utf8mb4

Below is the attached database.yml:

  
  production:

    url: <%= ENV['DATABASE_URL'] %>

    pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>

    checkout_timeout: <%= ENV['DB_CHECKOUT_TIMEOUT'] || 5 %>

    reaping_frequency: <%= ENV['DB_REAP_FREQ'] || 10 %>

I am using Sidekiq for processing the background jobs.

Anything that I missed? Any insights will be really helpful.

**Comment by kevinjcoleman** [comment]
@kavitakanojiya what error are you getting specifically? Also can your server access your `ENV['DATABASE_URL']` in production? Could be load balancer issue or something like that.

**Comment by canatella** [comment]
Hello, maybe same issue here:

```
I, [2018-12-03T08:23:30.618793 #27524]  INFO -- : Completed 500 Internal Server Error in 5002ms (ActiveRecord: 0.0ms)
F, [2018-12-03T08:23:30.619354 #27524] FATAL -- :
F, [2018-12-03T08:23:30.619391 #27524] FATAL -- : ActiveRecord::ConnectionTimeoutError (could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use):
F, [2018-12-03T08:23:30.619412 #27524] FATAL -- :
F, [2018-12-03T08:23:30.619452 #27524] FATAL -- : activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:199:in `block in wait_poll'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:190:in `loop'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:190:in `wait_poll'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:151:in `internal_poll'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:275:in `internal_poll'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:145:in `block in poll'
/opt/rubies/ruby-2.3.8/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:155:in `synchronize'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:145:in `poll'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:797:in `acquire_connection'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:521:in `checkout'
activerecord (5.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:380:in `connection'
ar-octopus (0.10.1) lib/octopus/proxy.rb:76:in `safe_connection'
ar-octopus (0.10.1) lib/octopus/proxy.rb:80:in `select_connection'
ar-octopus (0.10.1) lib/octopus/proxy.rb:312:in `block in send_queries_to_slave'
ar-octopus (0.10.1) lib/octopus/proxy.rb:345:in `using_shard'
ar-octopus (0.10.1) lib/octopus/proxy.rb:311:in `send_queries_to_slave'
ar-octopus (0.10.1) lib/octopus/proxy.rb:282:in `send_queries_to_selected_slave'
ar-octopus (0.10.1) lib/octopus/proxy.rb:223:in `legacy_method_missing_logic'
```

My shards: 

```
octopus:
  replicated: true
  fully_replicated: true
  environments:
    - reporting

  reporting:
    slave1:
      host: ...
      adapter: mysql2
      database: ...
      username: ...
      password: ...
```
It might be linked to https://github.com/rails/rails/pull/23807. It's working correctly for request on the main server, it's only when requesting to the slave that this occurs.

**Comment by tswayne** [comment]
@thiagopradi @kevinjcoleman also seeing the same behavior after bumping to rails 5.2 and octopus 10.1. 

 Only seeing this in sidekiq workers.  And we're only seeing the timeout when querying our sharded db.

**Comment by tswayne** [comment]
So, after some digging I've at least found part of the issue.  The shard's pool size is no longer being set by database.yml.  When logging our shard's pool size (`connection.pool.instance_variable_get('@size')}`) it was not what we had set in our database.yml.  Adding pool to our shards.yml fixed that issue.  I was hoping it would resolve the connection errors, but we're still seeing them.

**Comment by kavitakanojiya** [comment]
You need to set the pool in the octopus configuration. This can read the value that is used to configure the pool size of the database.yml.

**Comment by gabrielqueiroz** [comment]
I am facing the same issue with connection pools. Could anyone share an example with a project using Octopus and setting the pool size?

**Comment by Samy-Amar** [comment]
@tswayne How did you add pool to the shards.yml file? Is it simply by adding `pool: ` under the `slave1:` configuration?

**Comment by tswayne** [comment]
@Samy-Amar yep, that was it
