### ISSUE TITLE
Octopus.using inside rails console and worker dynos

### ISSUE THREAD

**Issue by knagode** [thiagopradi/octopus#514]
We are using Octopus with puma server on heroku. 

I needed to add some configuratio into `puma.rb` configuration file:

```
on_worker_boot do
  ActiveRecord::Base.establish_connection
  ActiveRecord::Base.connection.initialize_shards(Octopus.config)
end
```

However I noticed that `Octopus.using` raises an error if code is run on worker dyno or in rails console:

```
ActiveRecord::ConnectionNotEstablished: ActiveRecord::ConnectionNotEstablished
```

Should I put `ActiveRecord::Base.connection.initialize_shards(Octopus.config)` somewhere else?

We dynamically configure shard settings via `shards.rb` 

```
Octopus.setup do |config|
  config.environments = ...
  config.shards = ...
end
```

I see that if I triggering `ActiveRecord::Base.connection.initialize_shards(Octopus.config)` before running `Octopus.using` solves the issue but it doesn't seem like a good idea to me - I don't want to run initialization every time I use Octopus ...

**Comment by thiagopradi** [comment]
HI @knagode,

About the problem when using the console - that's weird. I think it might be related to the dynamic configuration of your shards. Can you try to add those lines above your shard configuration file to see if you still need to call those lines when opening a console? 

Thanks

**Comment by knagode** [comment]
@thiagopradi 	You are right. It was dynamic configuration problem. It seemed that everything worked but we had tons of silent errors with delayed job so we are not able to use it at the moment .. We will simply wait for Rails6

**Comment by thiagopradi** [comment]
@knagode - okay - cool. Closing this issue them.
