### ISSUE TITLE
Not able to access the wiki page

### ISSUE THREAD

**Issue by aksharj** [thiagopradi/octopus#523]
When trying to access the wiki page https://wiki.github.com/thiagopradi/octopus/, I see the following error "We didn't receive a proper request from your browser. Please contact us if the problem persists."

**Comment by Audrius** [comment]
:+1:

**Comment by shqear93** [comment]
same issue

**Comment by shqear93** [comment]
meanwhile, you can use change the link to access wiki pages as the following :
https://wiki.github.com/thiagopradi/octopus/sharding
to :
https://github.com/thiagopradi/octopus/wiki/sharding

in your case: https://github.com/thiagopradi/octopus/wiki

**Comment by thiagopradi** [comment]
Thanks for the report - the README file now as the updated links: https://github.com/thiagopradi/octopus/commit/1c0abed4a2cd58869b4aa05e46e1a49a2e0f670f.

Thiago
