### ISSUE TITLE
How does the ActiveRecord connection pool interact with Octopus?

### ISSUE THREAD

**Issue by UpQuark** [thiagopradi/octopus#534]
Hi folks,

I'm trying to pin down a slippery issue with a Rails API that's using Octopus to maintain a large (200+) list of SQL Server database shards for multitenancy. 

We host our application on MS Azure which has a limit of SNAT ports used for all outbound TCP connections (including DB connections) that we seem to be periodically exhausting. I understand ActiveRecord maintains a connection pool so that it can reuse connections when they complete queries, but I don't understand is how this intersects with Octopus.

For example, our Database.yml, which we load settings from when loading shards, sets the pool size at "5." We then apply these settings to each shard in a list of shard names, with the below code snippets:

Building the list of shards, where config is loaded from our database.yml:
```
def self._build_shards(db_names, config)
      shards = { ENV['RAILS_ENV'].to_sym => {} }
      db_names.each do |name|
        shards[ENV['RAILS_ENV'].to_sym][name] = {
          host:      config['host'],
          pool:      config['pool'],
          adapter:   config['adapter'],
          database:  name,
          username:  config['username'],
          password:  config['password'],
          port:      config['port'],
          azure:     config['azure'],
          timeout:   config['timeout'],
          variables: config['variables']
        }
      end
      return shards
    end
```

...saving the list of shards to octopus:
```
# Save shards to config
      Octopus.setup do |config|
        config.environments = [ENV['RAILS_ENV']]
        config.shards       = shards
      end
```

Is this maintaining essentially a separate connection for each database shard? Or is there a unified pool somehow?

Thanks much!

**Comment by woohoou** [comment]
@thiagopradi We have a similar problem here, can you explain how octopus work with the db pool?

**Comment by UpQuark** [comment]
Hey @woohoou, So I stepped through the source code a bit. As far as I can tell, each shard in the Octopus list of shards maintains its own ActiveRecord instance with its own connection pool. So there exists no construct of a single connection pool that would hold connections to more than one database. Setting the connection pool size variable (in our case in a database.yml file) sets the size of the pool for EACH shard, not overall.

**Comment by maxstudener** [comment]
I have an app that has over 600 clients and growing and we have hit the open file limit on the database server several times, I am currently looking for a better solution to connection pools. Right now we take the subdomain look for the shard and use that shard but this has become an issue. Any ideas on a better solution?

**Comment by UpQuark** [comment]
I'm going to close this as self-answered:

1. Octopus basically stores a big hash of ActiveRecord connection pools. So there is one *pool* per shard, meaning your total allocated connections will be up to `total shards * max connections per shard`.
2. Rails 6+ provides this feature and there's[ a working SQL Server adapter](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter) for Rails 6 for anyone for whom that was a blocker at some point.

Closing this issue. Thanks @thiagopradi for this useful little OSS library, I'm off it now but it lasted me a pretty respectful number of years without any incident!
