### ISSUE TITLE
octopus for ruby project

### ISSUE THREAD

**Issue by zheyiyi** [thiagopradi/octopus#551]
Can I use octopus for pure ruby project, not rails one?
But when I use, it said taht 
   
    module ActiveRecord
      class Base
         def self.with_readonly(&block)
      if @has_readonly_connection ||= Octopus.new.config[Rails.env].try(:keys).try(:include?, 'readonly')
        Octopus.new.using(:readonly) do
          block.call
        end
      else
        block.call
      end

uninitialized constant ActiveRecord::Base::Octopus.

**Comment by thiagopradi** [comment]
Octopus is designed to work on Ruby-only projects. You just need to create a `config/shards.yml` file with the config file: https://github.com/thiagopradi/octopus/wiki/Config-File and use the gem normally.
