### ISSUE TITLE
octopus 0.6.1 make rake unit test failling..

### ISSUE THREAD

**Issue by warm200** [thiagopradi/octopus#556]
in my test by ActiveSupport, some `stubs` is failling when asserting,
it's working in the test file iteslf, but when you check in the actual code, it's not stubbing at all
seems i am missing some configuration
rails-3.0.20
rake-10.5.0
activerecord-3.0.20
activesupport (3.0.20)

also printed `Octupos.enabled?` return false when i run `bundle exec rake test:units`.
i tried uninstall octupos, and everything is green, but some are failling just after installing octopus

any help would be appreciated.

**Comment by thiagopradi** [comment]
Rails 3 is not supported anymore - please upgrade to a newest version.

Thiago
