### ISSUE TITLE
no rails sql cache when reading from slaves

### ISSUE THREAD

**Issue by bdarrow** [thiagopradi/octopus#81]
Rails/activerecord typically caches SQL statements if they are identical in the same request.  Typically in the log it shows the query with the word 'CACHE' next to it for queries hitting the sql cache.  Using octopus in a fully replicated setup, the SQL cache is not used when reading from slaves.  Only read requests explicitly sent to the master ".using(:master)" provide caching (and similarly read requests in a transaction)

**Comment by knightq** [comment]
Please, @eprothro, update also [here](https://github.com/thiagopradi/octopus/wiki/Replication-with-Rails-on-Heroku/bbfed2f77f9e89cd6c3bfdcbe7c08f82da27bb1d#sql-caching) (no caveat from verison 0.7.0)

**Comment by eprothro** [comment]
@knightq feel free to update that, all users have edit access, I believe.

**Comment by ricardovj** [comment]
Has this been actually solved? We're still seeing negative performance when enabling Octopus, enough to cause us to have disable it now :(

**Comment by knagode** [comment]
I also have this same issue? Is this intended to be solved?
